version: '3.2'
services:
  user-app:
   image: gamedevil007/my-book-app:user-app
   restart: always
   network_mode: host
   ports:
     - 7070:7070
   expose:
     - 7070
   depends_on:
     - book-mysql
  book-app:
   image: gamedevil007/my-book-app:book-app
   restart: always
   network_mode: host
   ports:
     - 9090:9090
   expose:
     - 9090
   depends_on:
     - book-mysql

  book-mysql:
   image: mysql:5.5
   network_mode: host
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: bookdb
  angular:
    image: gamedevil007/my-book-app:angular-app
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
    expose:
     - 4200
